// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw1nC_8IwduSQ_D9kWp9S2uh3Lk4HEedE',
    appId: '1:527865829612:web:557a2e0facff489459adc9',
    messagingSenderId: '527865829612',
    projectId: 'gemini-styler',
    authDomain: 'gemini-styler.firebaseapp.com',
    storageBucket: 'gemini-styler.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKq3Y7zXr-LlW7Cqy-Ej23Ole-Ex0FxUU',
    appId: '1:527865829612:android:ac235cd9607b78ff59adc9',
    messagingSenderId: '527865829612',
    projectId: 'gemini-styler',
    storageBucket: 'gemini-styler.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnOnZjoREsOTvns6QxlTbjgn291tUfNEI',
    appId: '1:527865829612:ios:16e78e993fc50cca59adc9',
    messagingSenderId: '527865829612',
    projectId: 'gemini-styler',
    storageBucket: 'gemini-styler.appspot.com',
    iosBundleId: 'com.Sci3fic.geminiStyler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnOnZjoREsOTvns6QxlTbjgn291tUfNEI',
    appId: '1:527865829612:ios:16e78e993fc50cca59adc9',
    messagingSenderId: '527865829612',
    projectId: 'gemini-styler',
    storageBucket: 'gemini-styler.appspot.com',
    iosBundleId: 'com.Sci3fic.geminiStyler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw1nC_8IwduSQ_D9kWp9S2uh3Lk4HEedE',
    appId: '1:527865829612:web:b684bcad58eac00659adc9',
    messagingSenderId: '527865829612',
    projectId: 'gemini-styler',
    authDomain: 'gemini-styler.firebaseapp.com',
    storageBucket: 'gemini-styler.appspot.com',
  );
}
